### ISSUE TITLE
Encurtar links

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/GDGAjuBot#10]
Encurtar as URLs fornecidas pelo bot através do goo.gl ou serviço semelhante.

**Comment by wagnerluis1982** [comment]
Estou verificando se posso fazer isso. O ideal seria `goo.gl` por que estamos no GDG, mas não tem API e a adição de URLs é feita via JavaScript, além disso, sem autenticação, a página tem Captcha.

**Comment by wagnerluis1982** [comment]
Engano meu, parece que `goo.gl` tem API sim, o link https://developers.google.com/url-shortener/v1/getting_started#intro explica sobre.

**Comment by erickmendonca** [comment]
Boa! Eu vi que tinha gente que usava, mas estava incerto se era API ou fazendo posts na página :)

**Comment by wagnerluis1982** [comment]
Eu descobri uma alternativa. Não soluciona literalmente o problema, mas atenua.

De acordo com a API de bots, podemos usar formatação markdown na reposta. Assim, o link longo http://www.meetup.com/GDG-Aracaju/events/229313880/ se torna [Link](http://www.meetup.com/GDG-Aracaju/events/229313880/).

Isto pode ser feito com a marcação `[Texto](url)`.

Referência: https://core.telegram.org/bots/api#formatting-options

**Comment by erickmendonca** [comment]
Fiz o teste disso no /book, muito bom! De qualquer forma depois vou encurtar o link só pra ter o analytics dos cliques :)

**Comment by wagnerluis1982** [comment]
Concordo, mas acho que isso também é útil para os links curtos, que ainda são grandes para a tela de celular. Do meu, ao menos :-/

**Comment by erickmendonca** [comment]
Aham. Vou verificar se tem como remover a pré-visualização, ai já economizamos espaço.

**Comment by wagnerluis1982** [comment]
Eu pensei nisso também, sobre a remoção da pré-visualização.

**Comment by wagnerluis1982** [comment]
O meetup.com também possui um encurtador de url com o domínio meetu.ps, mas eu não consegui informações oficiais sobre como usar e se é um serviço aberto.

Eu percebi que quando se compartilha um evento pelo aplicativo do meetup no Android, a url repassada é curta, via meetu.ps
