### ISSUE TITLE
Atualizar parser do e-book para o novo formato usado pela PacktPub

### ISSUE THREAD

**Issue by wagnerluis1982** [GDGAracaju/GDGAjuBot#100]

**Comment by wagnerluis1982** [comment]
Identifiquei que não há mais informações do livro no HTML da página https://www.packtpub.com/packt/offers/free-learning

**Comment by wagnerluis1982** [comment]
Provavelmente as informações do livro estão ofuscadas em algum arquivo JS ou algo do tipo.

**Comment by gdgaracajugod** [comment]
Existe uma solução aqui: https://github.com/erickmendonca/GDGAjuBot/pull/6

**Comment by erickmendonca** [comment]
☝️ Eu escrevi aquela solução para testar um bot que faz merge de PRs automaticamente - com algum polimento e tests podemos trazê-la pra cá.

As informações dos livros gratuitos agora estão disponíveis em uma API, enquanto os dados dos livros vivem em outra.
