### ISSUE TITLE
Página do livro diário com informações vazias

### ISSUE THREAD

**Issue by Unanimad** [GDGAracaju/GDGAjuBot#101]
A um tempo o bot parou de notificar sobre os livros diários gratuitos. Consegui identificar que o problema é no request da página, a qual está retornando informações vazias sobre o livro.

https://github.com/GDGAracaju/GDGAjuBot/blob/e5cbc597f4084127400b29804d320e4be5a2e457/gdgajubot/data/resources.py#L120

**Comment by wagnerluis1982** [comment]
Relacionado a #100

**Comment by wagnerluis1982** [comment]
@Unanimad, obrigado pela ajuda.

Mas nesse caso específico, o problema já está identificado, que é o que trata a issue #100 (que eu estou investigando), por isso estou fechando esta daqui.

P.S.: tem várias outras issues abertas, toda ajuda é bem vinda.
