### ISSUE TITLE
Adicionar comando /auto-events

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/GDGAjuBot#11]
Este comando avisará de novidades no meetup automaticamente, um evento por vez ou periodicamente.

- [x] Comando /auto_events
- [x] Comando /auto_book
- [x] Configurar os comandos para só aceitar requisições de admins quando dentro de grupos.

**Comment by wagnerluis1982** [comment]
Estou confuso sobre o comportamento desse comando em relação ao `/events`.

1. `/auto-events` poderá ser chamado em grupos ou somente em private?
2. Poderemos cancelar o comando, isto é, o envio de notificações do meetup?
3. Depois que `/auto-events` for chamado, `/events` ainda funcionará?

**Comment by erickmendonca** [comment]
> 1. /auto-events poderá ser chamado em grupos ou somente em private?
Talvez seja melhor em private mesmo.

> 2. Poderemos cancelar o comando, isto é, o envio de notificações do meetup?
/auto-events pode ser um toggle então, se chamar de novo desabilita.

> 3. Depois que /auto-events for chamado, /events ainda funcionará?
Sim, apesar de redundante. É tipo ficar dando F5 no email :smile:

**Comment by wagnerluis1982** [comment]
Pode ser interessante habilitar `/auto_events` (e também `/auto_book`) em supergrupos: nesse caso seriam comandos restritos aos admins.

**Comment by erickmendonca** [comment]
Pode ser! A API tem essa informação, né?

**Comment by wagnerluis1982** [comment]
> Pode ser! A API tem essa informação, né?

Eu espero que sim! 😅
