### ISSUE TITLE
Link para última resposta de /events ou /books se não houve alteração

### ISSUE THREAD

**Issue by wagnerluis1982** [GDGAracaju/GDGAjuBot#12]
A ideia é fazer o seguinte. Se houver duas ou mais chamadas a /events com horários muito próximos e não houve alteração na resposta, então o bot irá responder vinculando a própria resposta anterior.

## Exemplo:

```
- user> /events
- bot>
  Evento 1 http://...
  Evento 2 http://...
  Evento 3 http://...
- user> /events
- bot> [bot Evento 1 ...]
  Clique para ver a última resposta
```

**Comment by erickmendonca** [comment]
Tem de controlar aonde ele postou, já que o bot pode ser usado fora do grupo, mas é bacana! Assim reduz a quantidade de texto.

**Comment by wagnerluis1982** [comment]
Rapaz, juro que esqueci que o bot não era propriedade exclusiva do grupo.

Mas uma ideia aqui é ignorar os chats privados, considerar apenas grupos.
Em 25/03/2016 13:30, "Erick Mendonça" <notifications@github.com> escreveu:

**Comment by erickmendonca** [comment]
Isso, e acho que a própria API avisa se é grupo ou chat :)
