### ISSUE TITLE
Revisar requisitos do projeto

### ISSUE THREAD

**Issue by wagnerluis1982** [GDGAracaju/GDGAjuBot#15]
A revisão dos requisitos seguem dois pontos, descritos a seguir.

1. Várias entradas do arquivo `requirements.txt` eu não vi serem usadas no código:

  ```
  MarkupSafe==0.23
  py==1.4.31
  pytest==2.8.5
  six==1.10.0
  wheel==0.26.0
  gunicorn==19.4.5
  ```

2. Algumas bibliotecas externas talvez possam ser substituídas por uma biblioteca padrão:
  - `requests` => `urllib.request`
  - `lxml` => alguma das bibliotecas em https://docs.python.org/3/library/markup.html

**Comment by erickmendonca** [comment]
Valeu @wagnerluis1982 por fazer esse levantamento! Realmente precisamos revisar algumas coisas aqui.

 - `gunicorn` é usado para fazer o deploy do web_dashboard
 - `requests`, `MarkupSafe`, `six`, `py` e `wheel` estão nos requirements do `pyTelegramBotAPI`. Alguns são desnecessários para o funcionamento da lib, mas são instalados por padrão
 - `py.test` também entrou pelo `pyTelegramBotAPI`, mas acho que podemos usá-los em nossos testes também.

**Comment by wagnerluis1982** [comment]
Eu não sou especialista em dependências de Python, mas é realmente preciso listar as dependências de outra dependência? O que eu quero dizer, listando apenas `pyTelegramBotAPI` o pip não vai instalar `requests`, `MarkupSafe`, `six`, `py`, `py.test` e `wheel` automaticamente?

Eu creio que seja assim, portuário seria mais correto listar apenas `pyTelegramBotAPI`, pois se ocorrer de trocarmos essa lib por outra, apenas trocamos uma lib pela outra no arquivo `requirements.txt`.

Concluindo, pelo que vi no uso de `requests` no script, pode ser substituído sem grandes problemas por `urllib.request`.

Sobre `lxml`, acho que o trabalho para instalar não compensa o ínfimo uso deste. E acho que poderíamos a substituir tranquilamente por um dos parsers da stdlib.

**Comment by erickmendonca** [comment]
Instala sim junto com a `pyTelegramBotAPI`, é que na hora que você executa `pip freeze` para ver as dependências instaladas atualmente, vem tudo :smiley: Podemos remover essas secundárias.

A `lxml` pode ser removida facilmente, olhei por cima e aparentemente não é uma dependência secundária. Já a `requests` é utilizada pela `pyTelegramBotAPI`, então não vamos ganhar muita coisa tirando ela do bot.

**Comment by wagnerluis1982** [comment]
Vou elencar o mínimo de dependências e criar o arquivo `minimum-requirements.txt`.

Outra alternativa é definir um `setup.py` com as dependências mínimas. Alguma preferência?

**Comment by wagnerluis1982** [comment]
Os requisitos mínimos foram inseridos no arquivo `setup.py`
