### ISSUE TITLE
Comando /refresh para limpar o cache

### ISSUE THREAD

**Issue by wagnerluis1982** [GDGAracaju/GDGAjuBot#31]
Sugiro a adição do comando `/refresh` para limpar o cache, forçando um novo download aos comandos `/events` e `/book`.

Isso será útil quando, por exemplo, em uma correção em um meetup de última hora.

O `/refresh` só deverá atender à solicitações em *private* e para usuários registrados.

**Comment by wagnerluis1982** [comment]
A classe `beaker.cache.CacheManager` não me oferece uma lista dos itens em cache ou mesmo uma opção para limpar o cache.

**Comment by wagnerluis1982** [comment]
Assim, as soluções que imagino são:

1. identificar como o beaker faz esse gerenciamento e utilizar, mas há o risco de utilizar estruturas internas que podem ser alteradas em atualizações.
2. criar um wrapper de `CacheManager` para rastrear quais caches criamos.

**Comment by erickmendonca** [comment]
Acho que podemos limitar o cache a no máximo 3 minutos, preferencialmente 1. Não vai doer muito e não precisa entrar no framework de cache tanto. Assim a gente lida com a hipótese de muitas solicitações simultâneas, sem perder a responsividade do bot.

**Comment by wagnerluis1982** [comment]
O cache pode ficar seletivo, /book pode ter um cache longo, uns 10 minutos, enquanto /events sim precisa ter um cache curto de 1 a 2 minutos.

**Comment by erickmendonca** [comment]
Acho válido! :+1:

**Comment by wagnerluis1982** [comment]
Outra coisa é que o beaker permite invalidar um cache, assim o cache de /book pode ser até eterno (ou bem longo), sendo invalidado se `expire_time > now` e exigido um novo valor do servidor.

**Comment by wagnerluis1982** [comment]
Pressupondo que a PR #41 será aceita, estou fechando essa issue.
