### ISSUE TITLE
Evitar chegar aos limites de envio do bot

### ISSUE THREAD

**Issue by wagnerluis1982** [GDGAracaju/GDGAjuBot#45]
De acordo com o FAQ do Telegram especializado a bots, há algumas limitações impostas ao envio de mensagens:
- Um bot **deve evitar** enviar mais de uma mensagem por segundo para um único chat.
- Um bot **não pode** enviar mais de 30 mensagens em um segundo.
- Um bot **não é capaz** de enviar mais de 20 mensagens por minuto a um mesmo chat.

Com a introdução dos comandos `/auto_book` e `auto_events`, o _gdgajubot_ pode perigosamente atingir esses limites, sendo impedido de enviar mensagens por algumas horas.

Link: https://core.telegram.org/bots/faq#broadcasting-to-users

**Comment by erickmendonca** [comment]
Bem observado!

**Comment by wagnerluis1982** [comment]
No final das contas esse problema não é tão complicado, mas só um pouco trabalhoso.

Com as modificações certas, a classe `TeleBot` terá seu comportamento alterado de forma que todas as mensagens "enviadas" serão na verdade inseridas numa fila (que chamo de principal).

Assim, uma *thread* separada consome a fila principal sem parar, fazendo o verdadeiro envio, mas atentando às restrições impostas pela API.

O algoritmo da imagem a seguir serve de ilustração para o que ficará sendo executado nessa *thread*.

![bug45-send](https://cloud.githubusercontent.com/assets/428341/15062170/dd0457b8-1313-11e6-814a-8aa104253346.png)

**Comment by wagnerluis1982** [comment]
Para que seja possível implementar, falta definir o algoritmo que verifica se a mensagem tem restrições para envio.

**Comment by wagnerluis1982** [comment]
Provavelmente essa issue foi resolvida com a mudança da biblioteca de bot, por isso vou fechar.
