### ISSUE TITLE
Aprimorar o README

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/GDGAjuBot#6]
Incluir uma melhor documentação, explicando como:

- [x] configurar parâmetros
- [x] executar o bot
- [x] obter os tokens do Telegram e Meetup
- [ ] opções de deploy
- [ ] como utilizar a web dashboard

**Comment by wagnerluis1982** [comment]
As três primeiras já foram colocadas no README.

Não sei direito o que quer dizer "opções de deploy" e como não conheço o web dashboard, não fiz esses dois.
