### ISSUE TITLE
Adicionar comando /auto-book

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/GDGAjuBot#7]
Esse comando registrará o usuário solicitante e enviará para ele o resultado de /book diariamente. 

Com esta opção podemos evitar parte do spam quando o bot for usado em grupos.

**Comment by wagnerluis1982** [comment]
Pelo que entendi, `/auto-book` será um comando exclusivamente para uso em private, correto?

**Comment by erickmendonca** [comment]
Poderia até ser em grupo, mas não sei se nesse caso realmente evitaria spam. Pensando bem, podemos limitar para cada usuário (e persistir isso entre sessões).

**Comment by wagnerluis1982** [comment]
Sobre persistir, você quer dizer, guardar para caso o bot seja reiniciado?
