### ISSUE TITLE
Exceção em /book quando não há livros disponíveis

### ISSUE THREAD

**Issue by wagnerluis1982** [GDGAracaju/GDGAjuBot#70]
O bot não responde quando não há livros disponíveis em PacktPub.

Esse bug deverá, preferencialmente, ser corrigido com a adição de testes unitários.

**Comment by erickmendonca** [comment]
@wagnerluis1982 Acho que o problema foi introduzido quando adicionamos a habilidade de capturar e enviar a imagem do livro na resposta do comando. Deve estar faltando uma condição para quando não há livro/imagem disponível.

**Comment by wagnerluis1982** [comment]
@erickmendonca Obrigado pela informação, vou corrigir esse bug amanhã!

**Comment by wagnerluis1982** [comment]
Issue corrigida na PR #71
