### ISSUE TITLE
Adicionar testes de unidade

### ISSUE THREAD

**Issue by erickmendonca** [GDGAracaju/GDGAjuBot#8]
Adicionar uma boa suíte de testes nos permitirá fazer deploys mais freqüentes do bot, possivelmente automatizados. 

Com esta suíte pronta, podemos inserir a regra de que qualquer novo PR só será aceito com seus devidos testes.

**Comment by wagnerluis1982** [comment]
Eu não consegui ver uma forma simples de adicionar testes, eu creio que será necessária uma grande refatoração no código, para modularizar, pois atualmente não dá para importar o módulo `gdgajubot.py` sem fazer toda a inicialização do bot (enviando requisições ao Telegram), porque `bot` é usado como decorator nas funções.

Talvez a melhor forma seja usar as funções sem decorator e utilizar algo como o seguinte (me baseei no README do pyTelegramBotAPI):

```python
# sem o decorator
def list_upcoming_events(message):
    ...

# sem o decorator
def packtpub_free_learning(message):
    ...

def handle_messages(messages):
    for message in messsages:
        if message.content_type == "text":
            if re.search(r"\events\b", message.text):
                return list_upcoming_events(message)
            elif re.search(r"\books\b", message.text):
                return packtpub_free_learning(message)

if __name__ == "__main__":
    bot.set_update_listener(handle_messages)
    bot.polling()
```

**Comment by wagnerluis1982** [comment]
Vi que `telebot.util` tem uma função chamada `extract_command` que facilita em identificar se o texto é um comando.

**Comment by erickmendonca** [comment]
Com certeza teremos de refatorar bastante. Bom fazer por agora enquanto é pequeno!

**Comment by wagnerluis1982** [comment]
Mas é preciso tomar uma direção de como isso será feito.

Acredito que o exemplo que dei, usando o loop `for message in messages`, é
a melhor solução, pois a solução não dependerá de um decorator (que tem que
existir no momento da definição).

Talvez haja outras soluções, na próxima semana vou olhar melhor o telebot,
e verificar.
Em 25/03/2016 13:32, "Erick Mendonça" <notifications@github.com> escreveu:

**Comment by wagnerluis1982** [comment]
Estou trabalhando nessa issue. Eu acho que o ideal seria agrupar os handlers em uma classe, mas inicialmente eu vou deixar direto no módulo mesmo.

**Comment by erickmendonca** [comment]
Acho que pode separar os métodos auxiliares dos que respondem aos comandos do bot, assim dá pra movermos isso pra outro módulo e testar separadamente.

**Comment by wagnerluis1982** [comment]
É justamente o que estou fazendo, estou separando os comandos anotados com `@bot` dos que realmente obtém os dados da Internet.

**Comment by wagnerluis1982** [comment]
Na outra issue, é mencionado usar `py.test`, mas eu sempre usei `nose`.
Você considera `py.test` melhor que `nose`?

NOTA: eu sempre usei `nose`, mas de forma retrocompatível com o `unittest` padrão do Python, de forma que o `nose` facilita minha vida, mas não é essencial.

**Comment by erickmendonca** [comment]
Entendi! Nunca comparei, estava usando o py.test por inércia.

**Comment by wagnerluis1982** [comment]
Bom, a saída dada pelo `unittest` padrão, usando `self.assertEqual`, etc. é melhor que os simples `assert`;
